config/routes.rb
Rails.application.routes.draw do
  resources :monuments
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/monument.rb
class Monument < ApplicationRecord
  validates :name, :address, :opening_date, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/monuments_controller.rb
class MonumentsController < ApplicationController
  before_action :set_monument, only: %i[show edit update destroy]

  # GET /monuments
  def index
    @monuments = Monument.all
    @new_monument = Monument.new
  end

  # GET /monuments/1
  def show
  end

  # GET /monuments/new
  def new
    @monument = Monument.new
  end

  # GET /monuments/1/edit
  def edit
  end

  # POST /monuments
  def create
    @monument = Monument.new(monument_params)

    respond_to do |format|
      if @monument.save
        format.html { redirect_to @monument, notice: "Monument was successfully created." }
        format.json # siga o padrão e busque uma view chamada create.json
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json # siga o padrão e busque uma view chamada create.json
      end
    end
  end

  # PATCH/PUT /monuments/1
  def update
    if @monument.update(monument_params)
      redirect_to @monument, notice: "Monument was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /monuments/1
  def destroy
    @monument.destroy!
    redirect_to monuments_url, notice: "Monument was successfully destroyed.", status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_monument
    @monument = Monument.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def monument_params
    params.require(:monument).permit(:name, :address, :opening_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Lww 1925 Javascript In Rails" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/monuments/_form.html.erb
<%= simple_form_for monument, data: { insert_in_list_target: 'form', action: 'submit->insert-in-list#send' } do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :opening_date, as: :string, input_html: { data: { controller: 'datepicker' } } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/monuments/_monument_info.html.erb
<div id="<%= dom_id monument_local %>">
  <p>
    <strong>Nome:</strong>
    <%= monument_local.name %>
  </p>

  <p>
    <strong>Endereço:</strong>
    <%= monument_local.address %>
  </p>

  <p>
    <strong>Data de abertura:</strong>
    <%= monument_local.opening_date %>
  </p>

</div>

app/views/monuments/edit.html.erb
<% content_for :title, "Editing monument" %>

<h1>Editing monument</h1>

<%= render "form", monument: @monument %>

<br>

<div>
  <%= link_to "Show this monument", @monument %> |
  <%= link_to "Back to monuments", monuments_path %>
</div>

app/views/monuments/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Monuments" %>

<h1>Monuments</h1>

<div data-controller="insert-in-list">
  <div id="monuments" data-insert-in-list-target="items">
    <% @monuments.each do |current_monument| %>
      <%= render 'monument_info', monument_local: current_monument %>
      <p>
        <%= link_to "Show this monument", monument_path(current_monument) %>
      </p>
    <% end %>
  </div>

  <div data-controller="toggle">
    <button class="btn btn-primary" data-action="click->toggle#fire">Add a new monument</button>
    <div data-toggle-target="togglableElement" class="d-none">
      <%= render 'form', monument: @new_monument %>
    </div>
</div>
</div>

app/views/monuments/new.html.erb
<% content_for :title, "New monument" %>

<h1>New monument</h1>

<%= render "form", monument: @monument %>

<br>

<div>
  <%= link_to "Back to monuments", monuments_path %>
</div>

app/views/monuments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render 'monument_info', monument_local: @monument %>

<div>
  <%= link_to "Edit this monument", edit_monument_path(@monument) %> |
  <%= link_to "Back to monuments", monuments_path %>

  <%= button_to "Destroy this monument", monument_path(@monument), method: :delete %>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>